api_controllers:
    resource: ../src/API/Controller/
    type: annotation
    prefix: api/

roku_controllers:
    resource: ../src/RokuDP/
    type: annotation
    prefix: roku/

api_login_check:
    path: /api/login

kernel:
    resource: ../src/Kernel.php
    type: annotation
